version: '3'
services:
    php:
        image:  trubkin/sotbit_php
        volumes:
          - ./sites:/var/www
        ports:
            - '9999:9000'
    web_server:
        image:  trubkin/sotbit_web_server
        depends_on:
            - php
        volumes:
          - ./sites:/var/www
        ports:
            - '80:80'
    db:
        image: trubkin/sotbit_db
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --sql-mode=""
        volumes:
            - ./data:/var/lib/mysql 
    # memcached:
    #     image: memcached:1.6.12-alpine
    #     container_name: sotbit_memcached
    #     volumes_from:
    #         - source
    #     ports:
    #         - '${INTERFACE}:11211:11211'
    #     networks:
    #         - bitrix
    #     restart: always
    # adminer:
    #     image: dockette/adminer:full
    #     container_name: sotbit_adminer
    #     links:
    #         - db:db
    #     ports:
    #         - '${INTERFACE}:8080:80'
    #     environment:
    #         UPLOAD: 1024M # upload_max_filesize, post_max_size
    #     networks:
    #         - bitrix
    # source:
    #     image: alpine:latest
    #     container_name: sotbit_source
    #     volumes:
    #         - ./logs/nginx:/var/log/nginx
    #         - ./logs/php:/var/log/php
    #         - ./logs/db:/var/log/mysql
    #         - ./logs/memcached:/var/log/memcached
    #         - db:/var/lib/mysql
    #         - cache:/var/lib/memcached
    #         #- ./www/html:/var/www/html
    #         - C:/for_docker/sites:/var/www/
    #         - /etc/localtime:/etc/localtime/:ro
    #     networks:
    #         - bitrix

volumes:
    db:
        driver: local
    cache:
        driver: local
    php:
        driver: local
    web_server:
        driver: local


# networks:
#     bitrix:
#         driver: bridge
#         ipam:
#             driver: default
#             config:
#                 - subnet: 10.100.0.0/24